# Generated by Django 6.0.4 on 2026-04-16 08:37

import django.db.models.deletion
import userAPI.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Match',
            },
        ),
        migrations.CreateModel(
            name='Relationship_preference',
            fields=[
                ('preference_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Relationship_preference',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('photo_student_id', models.ImageField(upload_to=userAPI.utilities.fileRename)),
                ('photo_id_selfie', models.ImageField(upload_to=userAPI.utilities.fileRename)),
                ('id_student', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surnames', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('school_name', models.CharField(max_length=150)),
                ('gender', models.CharField(default='', max_length=10)),
                ('biography', models.CharField(max_length=150)),
                ('height', models.CharField(default='', max_length=5)),
                ('date_of_birth', models.DateField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('profile_pic', models.TextField()),
                ('max_distance_km', models.IntegerField(default='')),
                ('show_me', models.BooleanField(default=True)),
                ('likes', models.IntegerField(default=0)),
                ('restricted', models.BooleanField(default=False)),
                ('restricted_reason', models.CharField(max_length=100)),
                ('restricted_at', models.DateField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userAPI.user')),
                ('amount_tabs', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'User_card',
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('matched', models.BooleanField()),
                ('pk', models.CompositePrimaryKey('origin_user_id', 'target_user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('origin_user_id', models.ForeignKey(db_column='origin_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='origin_user_id', to='userAPI.user')),
                ('target_user_id', models.ForeignKey(db_column='target_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_user_id', to='userAPI.user')),
            ],
            options={
                'db_table': 'Swipe',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('currently_studying', models.BooleanField(default=False)),
                ('pk', models.CompositePrimaryKey('user_id', 'name', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'Study',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id_photo', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('visible', models.BooleanField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField()),
                ('id_next_message', models.ForeignKey(db_column='id_next_message', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userAPI.message')),
                ('id_previous_message', models.ForeignKey(db_column='id_previous_message', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userAPI.message')),
                ('match_id', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.match')),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='user1_id',
            field=models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='user1_id', to='userAPI.user'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_id',
            field=models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='user2_id', to='userAPI.user'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('pk', models.CompositePrimaryKey('user_id', 'name', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('description', models.CharField(max_length=100)),
                ('pk', models.CompositePrimaryKey('user_id', 'description', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'Goal',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('reason', models.CharField(max_length=100)),
                ('pk', models.CompositePrimaryKey('id_logged_user', 'id_blocked_user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_blocked_user', models.ForeignKey(db_column='id_blocked_user', on_delete=django.db.models.deletion.CASCADE, related_name='id_blocked_user', to='userAPI.user')),
                ('id_logged_user', models.ForeignKey(db_column='id_logged_user', on_delete=django.db.models.deletion.CASCADE, related_name='id_logged_user', to='userAPI.user')),
            ],
            options={
                'db_table': 'Block',
            },
        ),
        migrations.CreateModel(
            name='User_relation_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.relationship_preference')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
            options={
                'db_table': 'User_relation_preference',
            },
        ),
        migrations.CreateModel(
            name='CardTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=50)),
                ('sub_header', models.CharField(max_length=50)),
                ('tab_biography', models.CharField(max_length=100)),
                ('background_photo', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.usercard')),
            ],
            options={
                'db_table': 'Card_tab',
            },
        ),
    ]
