# Generated by Django 6.0.4 on 2026-04-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__941e05_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_timesta_6494d7_idx',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
